import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
const Landing = dynamic(() => import('@/components/Landing/Landing'), {
  ssr: false,
});
import Creator from '@/components/Creator/Creator'
import Features from '@/components/Features/Features'
import Works from '@/components/Works/Works'
import Dive from '@/components/Dive/Dive'
import Faq from '@/components/FAQ/Faq'
import Faqs from '@/components/FAQ/Faq'
import Footer from '@/components/Footer/Footer'
import Header from '@/components/Header/Header'
import dynamic from 'next/dynamic';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
     <Landing/>
     <Creator/>
     <Features/>
     <Works/>
     <Dive/>
     <Faqs/>
     <Footer/>
    </>
  )
}
